
-- Physics engine constant

PHYSICS_ENGINE_PATH = "Engine/Physics/"

        -- LINUX SPEED CONFIG
--[[ HORIZONTAL_SPEED_MAX = 500
VERTICAL_SPEED_MAX = 2000

GRAVITY_SPEED = 50
GRAVITY_MAX = 300 ]]

        -- WINDOWS SPEED CONFIG
HORIZONTAL_SPEED_MAX = 800
VERTICAL_SPEED_MAX = 2000

GRAVITY_SPEED = 50
GRAVITY_MAX = 1000

-- Game update constant

FPS = 60

-- Graphics engine constant

GRAPHICS_ENGINE_PATH = "Engine/Graphics/"